#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2022/5/21 17:13
# @Author  : jjc
# @File    : mainWin.py
# @Software: PyCharm
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QDialog, QMessageBox
from signalManager import SignalManager
from title import OneTitle


class MainWin(QMainWindow, QDialog):

    def __init__(self):
        super(MainWin, self).__init__()
        self.setObjectName("main_window")
        self.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(self)
        self.central_widget.setObjectName("central_widget")
        self.chapter_frame = QtWidgets.QFrame(self.central_widget)
        self.chapter = QtWidgets.QPushButton(self.chapter_frame)
        self.chapter_font = QtGui.QFont()
        self.chapter_container = QtWidgets.QFrame(self.central_widget)
        self.sub_titles = QtWidgets.QScrollArea(self.chapter_container)
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.title_arr = []
        self.title_set = set()
        self.add_sub_title = QtWidgets.QPushButton(self.scroll_area_widget_contents)
        self.note_content = QtWidgets.QLabel(self.chapter_container)

    def add_title_btn(self, title_info):
        btn_text_name, content = title_info

        if btn_text_name:
            height_space = 40
            btn_pos_y = 50
            if self.title_arr:
                btn_pos_y = self.title_arr[-1].title_btn.y() + height_space
            push_button = QtWidgets.QPushButton(self.scroll_area_widget_contents)
            push_button.setObjectName(btn_text_name)
            push_button.setGeometry(QtCore.QRect(10, btn_pos_y, 111, 31))
            push_button.setText(btn_text_name)
            push_button.setStyleSheet("border:10px;\nborder:1px solid rgb(0, 0, 0);\n")
            push_button.show()
            browser = QtWidgets.QTextBrowser(self.chapter_container)
            browser.setGeometry(QtCore.QRect(150, 0, 621, 431))
            browser.setObjectName("context")
            browser.setMarkdown(content)
            browser.show()
            # 将之前的textBrowser隐藏，只显示新增的
            if self.title_arr:
                self.title_arr[-1].browser_content.hide()
            one_title = OneTitle(push_button, browser)
            self.title_arr.append(one_title)

    def _init_add_note_btn(self):
        self.add_sub_title.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.add_sub_title.setStyleSheet("border:10px;\nborder:1px solid rgb(0, 0, 0);\n")
        self.add_sub_title.setObjectName("add_sub_title")

    def _init_chapter_frame(self):
        self.chapter_frame.setGeometry(QtCore.QRect(10, 10, 771, 101))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.chapter_frame.sizePolicy().hasHeightForWidth())
        self.chapter_frame.setSizePolicy(size_policy)
        self.chapter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chapter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chapter_frame.setObjectName("chapter_frame")

    def _init_chapter(self):
        self.chapter.setGeometry(QtCore.QRect(0, 0, 181, 101))
        self.chapter_font.setFamily("楷体")
        self.chapter_font.setPointSize(24)
        self.chapter.setFont(self.chapter_font)
        self.chapter.setStyleSheet("border-radius:5px;\nborder:1px solid")
        self.chapter.setObjectName("chapter")

    def _init_chapter_container(self):
        self.chapter_container.setGeometry(QtCore.QRect(0, 120, 771, 431))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(5)
        size_policy.setHeightForWidth(self.chapter_container.sizePolicy().hasHeightForWidth())
        self.chapter_container.setSizePolicy(size_policy)
        self.chapter_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chapter_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chapter_container.setObjectName("chapter_container")

    def _init_sub_titles(self):
        self.sub_titles.setGeometry(QtCore.QRect(10, 0, 131, 421))
        self.sub_titles.setWidgetResizable(True)
        self.sub_titles.setObjectName("sub_title")
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 129, 419))
        self.scroll_area_widget_contents.setObjectName("scrollAreaWidgetContents")
        self.sub_titles.setWidget(self.scroll_area_widget_contents)

    def _init_note_content(self):
        self.note_content.setGeometry(QtCore.QRect(150, 10, 601, 401))
        self.note_content.setAlignment(QtCore.Qt.AlignCenter)
        self.note_content.setObjectName("note_content")

    def _init_menubar(self):
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNewChapter = QtWidgets.QAction(self)
        self.actionNewChapter.setObjectName("actionNewChapter")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNewChapter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

    def setup_ui(self):
        self._init_chapter_frame()
        self._init_chapter()
        self._init_chapter_container()
        self._init_sub_titles()
        self._init_add_note_btn()
        self._init_note_content()
        self.setCentralWidget(self.central_widget)
        self._init_menubar()
        self.re_translate_ui(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def re_translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.chapter.setText(_translate("main_window", "PyQt5"))
        # self.pushButton_4.setText(_translate("main_window", "PushButton"))
        # self.pushButton_5.setText(_translate("main_window", "ToolButton"))
        # self.pushButton_6.setText(_translate("main_window", "PushButton"))
        self.add_sub_title.setText(_translate("main_window", "添加"))
        self.note_content.setText(_translate("main_window", "请添加组件"))
        self.menuFile.setTitle(_translate("main_window", "File"))
        self.menuEdit.setTitle(_translate("main_window", "Edit"))
        self.menuWindow.setTitle(_translate("main_window", "Window"))
        self.menuHelp.setTitle(_translate("main_window", "Help"))
        self.actionOpen.setText(_translate("main_window", "Open"))
        self.actionNewChapter.setText(_translate("main_window", "NewChapter"))
