#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2022/5/21 17:13
# @Author  : jjc
# @File    : mainWin.py
# @Software: PyCharm
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QDialog, QWidget
from chapter import OneChapter


class MainWin(QMainWindow, QDialog):

    def __init__(self):
        super(MainWin, self).__init__()
        self.setObjectName("main_window")
        self.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(self)
        self.central_widget.setObjectName("central_widget")
        self.theme_frame = QtWidgets.QFrame(self.central_widget)
        self.theme = QtWidgets.QPushButton(self.theme_frame)
        self.theme_font = QtGui.QFont()
        self.theme_container = QtWidgets.QFrame(self.central_widget)
        self.sub_chapters = QtWidgets.QScrollArea(self.theme_container)
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.chapter_arr = []
        self.chapter_set = set()
        self.add_sub_chapter = QtWidgets.QPushButton(self.scroll_area_widget_contents)
        self.note_content = QtWidgets.QLabel(self.theme_container)

    def add_chapter_btn(self, chapter_info):
        btn_text_name, content = chapter_info

        if btn_text_name:
            height_space = 40
            btn_pos_y = 50
            if self.chapter_arr:
                btn_pos_y = self.chapter_arr[-1].chapter_btn.y() + height_space
            push_button = QtWidgets.QPushButton(self.scroll_area_widget_contents)
            push_button.setObjectName(btn_text_name)
            push_button.setGeometry(QtCore.QRect(10, btn_pos_y, 111, 31))
            push_button.setText(btn_text_name)
            push_button.setStyleSheet("border:10px;\nborder:1px solid rgb(0, 0, 0);\n")
            push_button.show()
            browser = QtWidgets.QTextBrowser(self.theme_container)
            browser.setGeometry(QtCore.QRect(150, 0, 621, 431))
            browser.setObjectName("context")
            browser.setMarkdown(content)
            browser.show()
            # 将之前的textBrowser隐藏，只显示新增的
            if self.chapter_arr:
                self.chapter_arr[-1].browser_content.hide()
            one_chapter = OneChapter(push_button, browser)
            self.chapter_arr.append(one_chapter)
            self._set_sub_chapter_scroll()

    def _init_add_note_btn(self):
        self.add_sub_chapter.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.add_sub_chapter.setStyleSheet("border:10px;\nborder:1px solid rgb(0, 0, 0);\n")
        self.add_sub_chapter.setObjectName("add_sub_chapter")

    def _init_theme_frame(self):
        self.theme_frame.setGeometry(QtCore.QRect(10, 10, 771, 101))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.theme_frame.sizePolicy().hasHeightForWidth())
        self.theme_frame.setSizePolicy(size_policy)
        self.theme_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.theme_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.theme_frame.setObjectName("theme_frame")

    def _init_theme(self):
        self.theme.setGeometry(QtCore.QRect(0, 0, 181, 101))
        self.theme_font.setFamily("楷体")
        self.theme_font.setPointSize(24)
        self.theme.setFont(self.theme_font)
        self.theme.setStyleSheet("border-radius:5px;\nborder:1px solid")
        self.theme.setObjectName("theme")

    def _init_theme_container(self):
        self.theme_container.setGeometry(QtCore.QRect(0, 120, 771, 431))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(5)
        size_policy.setHeightForWidth(self.theme_container.sizePolicy().hasHeightForWidth())
        self.theme_container.setSizePolicy(size_policy)
        self.theme_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.theme_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.theme_container.setObjectName("theme_container")

    def _init_sub_chapters(self):
        self.sub_chapters.setGeometry(QtCore.QRect(10, 0, 131, 421))
        self.sub_chapters.setWidgetResizable(True)
        self.sub_chapters.setObjectName("sub_chapter")
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 129, 419))
        self.scroll_area_widget_contents.setObjectName("scrollAreaWidgetContents")
        self._set_sub_chapter_scroll()
        self.sub_chapters.setWidget(self.scroll_area_widget_contents)

    def _set_sub_chapter_scroll(self):
        chapter_count = len(self.chapter_arr)
        self.scroll_area_widget_contents.setMinimumSize(10, 50 * chapter_count)

    def _init_note_content(self):
        self.note_content.setGeometry(QtCore.QRect(150, 10, 601, 401))
        self.note_content.setAlignment(QtCore.Qt.AlignCenter)
        self.note_content.setObjectName("note_content")

    def _init_menubar(self):
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNewtheme = QtWidgets.QAction(self)
        self.actionNewtheme.setObjectName("actionNewtheme")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNewtheme)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

    def setup_ui(self):
        self._init_theme_frame()
        self._init_theme()
        self._init_theme_container()
        self._init_sub_chapters()
        self._init_add_note_btn()
        self._init_note_content()
        self.setCentralWidget(self.central_widget)
        self._init_menubar()
        self.re_translate_ui()
        QtCore.QMetaObject.connectSlotsByName(self)

    def re_translate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("main_window", "MainWindow"))
        self.theme.setText(_translate("main_window", "PyQt5"))
        self.add_sub_chapter.setText(_translate("main_window", "添加"))
        self.note_content.setText(_translate("main_window", "请添加组件"))
        self.menuFile.setTitle(_translate("main_window", "File"))
        self.menuEdit.setTitle(_translate("main_window", "Edit"))
        self.menuWindow.setTitle(_translate("main_window", "Window"))
        self.menuHelp.setTitle(_translate("main_window", "Help"))
        self.actionOpen.setText(_translate("main_window", "Open"))
        self.actionNewtheme.setText(_translate("main_window", "Newtheme"))
