#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2022/5/28 16:47
# @Author  : jjc
# @File    : add_theme_dialog.py
# @Software: PyCharm
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\theme_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QMessageBox
from signal_manager import SignalManager


class AddThemeDialog(QMainWindow):
    def __init__(self, theme_set):
        super().__init__()
        self.setObjectName("add_theme_dialog")
        self.resize(400, 180)
        self.widget = QtWidgets.QWidget(self)

        self.grid_layout = QtWidgets.QGridLayout(self.widget)

        self.frame = QtWidgets.QFrame(self.widget)

        self.btn_frame = QtWidgets.QFrame(self.widget)

        self.theme_grid_layout = QtWidgets.QGridLayout(self.frame)
        self.label = QtWidgets.QLabel(self.frame)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)

        self.btn_grid_layout = QtWidgets.QGridLayout(self.btn_frame)
        self.save_btn = QtWidgets.QPushButton(self.btn_frame)
        self.cancel_btn = QtWidgets.QPushButton(self.btn_frame)

        self.send = SignalManager()
        self.theme_set = theme_set

    def setup_ui(self):
        self._init_widget()
        self._init_grid_layout()
        self._init_frame()
        self._init_btn_frame()
        self._init_label()
        self._init_input_edit()
        self._init_theme_grid_layout()
        self._init_save_btn()
        self._init_cancel_btn()
        self._init_btn_grid_layout()
        self.re_translate_ui()
        QtCore.QMetaObject.connectSlotsByName(self)

    def re_translate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请输入主题："))
        self.save_btn.setText(_translate("Dialog", "保存"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))

    def save_theme(self):
        theme_name = self.lineEdit.text()
        if theme_name in self.theme_set:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "主题已存在请重新输入")
            msg_box.exec_()
        elif len(theme_name) > 15:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "标题长度不能大于15个字符")
            msg_box.exec_()
        elif theme_name:
            self.theme_set.add(theme_name)
            self.send.send_theme_name(theme_name)
            self.lineEdit.clear()
            self.close()
        else:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "文章主题不能为空")
            msg_box.exec_()

    def close_dialog(self):
        self.close()

    def _init_widget(self):
        self.widget.setGeometry(QtCore.QRect(10, 20, 381, 151))
        self.widget.setObjectName("widget")

    def _init_grid_layout(self):
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("add_theme_grid_layout")
        self.grid_layout.addWidget(self.frame, 0, 0, 1, 1)
        self.grid_layout.addWidget(self.btn_frame, 1, 0, 1, 1)

    def _init_frame(self):
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

    def _init_btn_frame(self):
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")

    def _init_label(self):
        self.label.setObjectName("label")

    def _init_input_edit(self):
        self.lineEdit.setObjectName("lineEdit")

    def _init_theme_grid_layout(self):
        self.theme_grid_layout.setObjectName("theme_grid_layout")
        self.theme_grid_layout.addWidget(self.label)
        self.theme_grid_layout.addWidget(self.lineEdit)

    def _init_save_btn(self):
        self.save_btn.setObjectName("save_btn")
        self.save_btn.clicked.connect(self.save_theme)

    def _init_cancel_btn(self):
        self.cancel_btn.setObjectName("cancel_btn")
        self.cancel_btn.clicked.connect(self.close_dialog)

    def _init_btn_grid_layout(self):
        self.btn_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.btn_grid_layout.setObjectName("btn_grid_layout")
        self.btn_grid_layout.addWidget(self.save_btn, 0, 0, 1, 1)
        self.btn_grid_layout.addWidget(self.cancel_btn, 0, 1, 1, 1)
