# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_note_dialog.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMainWindow, QMessageBox, QWidget, QFrame, QFormLayout, QHBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from PyQt5.QtWidgets import QGridLayout
from PyQt5.QtGui import QTextCursor
from PyQt5.QtCore import QSize
from signal_manager import SignalManager
from db_model.chapter_note import ChapterNote


class AddNoteDialog(QMainWindow):

    def __init__(self, chapter_set):
        super(AddNoteDialog, self).__init__()
        self.setObjectName("add_note_dialog")
        self.resize(801, 455)
        self.central_widget = QWidget(self)
        self.central_widget.setObjectName("central_widget")

        self.font = QtGui.QFont()

        self.grid_layout = QGridLayout(self.central_widget)
        self.grid_layout.setObjectName("gird_layout")

        self.title_frame = QFrame(self.central_widget)
        self.content_frame = QFrame(self.central_widget)
        self.btn_frame = QFrame(self.central_widget)

        self.from_layout = QFormLayout(self.title_frame)

        self.horizontal_layout = QHBoxLayout(self.content_frame)

        self.btn_layout = QHBoxLayout(self.btn_frame)

        self.title_name_label = QtWidgets.QLabel(self.title_frame)

        self.title_line_edit = QtWidgets.QLineEdit(self.title_frame)

        self.note_content_label = QtWidgets.QLabel(self.content_frame)

        self.note_text_edit = QtWidgets.QTextEdit(self.content_frame)

        self.preview_label = QtWidgets.QLabel(self.content_frame)

        self.preview_note = QtWidgets.QTextBrowser(self.content_frame)

        self.save_note_btn = QtWidgets.QPushButton(self)

        self.cancel_note_btn = QtWidgets.QPushButton(self)

        self.send = SignalManager()
        self.chapter_set = chapter_set

    def show_dialog(self, theme_name):
        if theme_name:
            self.show()
        else:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "主题不存在，请先创建")
            msg_box.exec_()

    def _init_font(self):
        self.font.setFamily("宋体")
        self.font.setPointSize(18)
        self.font.setBold(True)
        self.font.setWeight(75)
        self.setFont(self.font)

    def _init_title_frame(self):
        self.title_frame.setObjectName("title_frame")
        self.title_frame.setMinimumSize(QSize(800, 50))
        self.title_frame.setMaximumSize(QSize(16777215, 50))
        self.title_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_frame.setFrameShape(QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QFrame.Raised)

    def _init_content_frame(self):
        self.content_frame.setObjectName(u"content_frame")
        self.content_frame.setMinimumSize(QSize(830, 450))
        self.content_frame.setFrameShape(QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QFrame.Raised)

    def _init_btn_frame(self):
        self.btn_frame.setObjectName(u"btn_frame")
        self.btn_frame.setMinimumSize(QSize(830, 50))
        self.btn_frame.setMaximumSize(QSize(16777215, 16777215))
        self.btn_frame.setFrameShape(QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QFrame.Raised)

    def _init_frame_layout(self):
        self.grid_layout.addWidget(self.title_frame, 0, 0, 1, 1)
        self.grid_layout.addWidget(self.content_frame, 1, 0, 1, 1)
        self.grid_layout.addWidget(self.btn_frame, 2, 0, 1, 1)

    def _init_title_layout(self):
        self.from_layout.setObjectName("from_layout")
        self.from_layout.setContentsMargins(9, -1, -1, -1)
        self.from_layout.setWidget(0, QFormLayout.LabelRole, self.title_name_label)
        self.from_layout.setWidget(0, QFormLayout.FieldRole, self.title_line_edit)

    def _init_content_layout(self):
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.horizontal_layout.addWidget(self.note_content_label, 0, QtCore.Qt.AlignTop)
        self.horizontal_layout.addWidget(self.note_text_edit)
        self.horizontal_layout.addWidget(self.preview_label, 0, QtCore.Qt.AlignTop)
        self.horizontal_layout.addWidget(self.preview_note)

    def _init_btn_layout(self):
        self.btn_layout.setObjectName("btn_layout")
        self.btn_layout.addWidget(self.save_note_btn)
        self.btn_layout.addWidget(self.cancel_note_btn)

    def _init_title_name_label(self):
        self.title_name_label.setObjectName("title_name_label")
        self.title_name_label.setMaximumSize(QSize(100, 16777215))
        self.title_name_label.setFont(self.font)

    def _init_title_edit(self):
        self.title_line_edit.setObjectName(u"title_line_edit")
        self.title_line_edit.setMinimumSize(QSize(200, 30))
        self.title_line_edit.setMaximumSize(QSize(100, 16777215))
        self.title_line_edit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)

    def _init_note_content_label(self):
        self.note_content_label.setObjectName("note_content_label")
        self.note_content_label.setMaximumSize(QSize(16777215, 50))
        self.note_content_label.setFont(self.font)

    def _init_note_content_edit(self):
        self.note_text_edit.setObjectName("note_text_edit")
        self.note_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.note_text_edit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.note_text_edit.textChanged.connect(self.fresh_text_edit)

    def _init_preview_note_label(self):
        self.preview_label.setObjectName("preview_label")
        self.preview_label.setMaximumSize(QSize(16777215, 50))
        self.preview_label.setFont(self.font)

    def _init_preview_note(self):
        self.preview_note.setObjectName("preview_note")
        # 设置水平滚动条
        self.preview_note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.preview_note.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.preview_note.verticalScrollBar().setValue(self.preview_note.verticalScrollBar().maximum())
        self.preview_note.moveCursor(QTextCursor.End)

    def _save_btn(self):
        self.save_note_btn.setObjectName(u"save_note_btn")
        self.save_note_btn.setMaximumSize(QSize(100, 16777215))
        self.save_note_btn.clicked.connect(self.save_title_content)

    def _cancel_btn(self):
        self.cancel_note_btn.setObjectName(u"cancel_note_btn")
        self.cancel_note_btn.setMaximumSize(QSize(100, 16777215))
        self.cancel_note_btn.clicked.connect(self.close_dialog)

    def setup_ui(self):
        self._init_font()
        self._init_title_frame()
        self._init_content_frame()
        self._init_btn_frame()
        self._init_frame_layout()
        self._init_title_layout()
        self._init_content_layout()
        self._init_btn_layout()
        self._init_title_name_label()
        self._init_title_edit()
        self._init_note_content_label()
        self._init_note_content_edit()
        self._init_preview_note_label()
        self._init_preview_note()
        self._save_btn()
        self._cancel_btn()
        self.re_translate_ui()
        self.setCentralWidget(self.central_widget)
        QtCore.QMetaObject.connectSlotsByName(self)

    def re_translate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("add_note_dialog", "Dialog"))
        self.title_name_label.setText(_translate("add_note_dialog", "标题名："))
        self.note_content_label.setText(_translate("add_note_dialog", "内容："))
        self.preview_label.setText(_translate("add_note_dialog", "预览："))
        self.save_note_btn.setText(_translate("add_note_dialog", "保存"))
        self.cancel_note_btn.setText(_translate("add_note_dialog", "取消"))

    def save_title_content(self):
        title_name = self.title_line_edit.text()
        content_txt = self.note_text_edit.toPlainText()
        if title_name in self.chapter_set:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "标题已存在请重新输入")
            msg_box.exec_()
        elif len(title_name) > 20:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "标题长度不能大于20个字符")
            msg_box.exec_()
        elif title_name and content_txt:
            self.send.send_signal((self.title_line_edit.text(), content_txt))
            self.title_line_edit.clear()
            self.note_text_edit.clear()
            self.close()
        else:
            msg_box = QMessageBox(QMessageBox.Warning, "警告", "文章标题和内容不能为空")
            msg_box.exec_()

    def close_dialog(self):
        self.close()

    def fresh_text_edit(self):
        self.preview_note.setText(self.note_text_edit.toPlainText())
        self.preview_note.setMarkdown(self.preview_note.toPlainText())
        # 保证预览界面与输入界面同步
        self.preview_note.verticalScrollBar().setValue(self.preview_note.verticalScrollBar().maximum())
        self.preview_note.moveCursor(QTextCursor.End)
